
# Fill with your bot token
# Create your bot by sending commands to @BotFather in Telegram
bot_token: "5741235458:AAHDcNdzR5fEnXgKoW9-xcEtAyKa9-KKFFk"

group_chat_id: "-896957151"

whisp_chat_id: "626778001"

# Fill with refresh seconds
refresh_seconds: 0.1

version: "v1.2.0-20221208"

timezone: "Asia/Taipei"

