
# Fill with your bot token
# Create your bot by sending commands to @BotFather in Telegram
# The following text and numbers are fake data for illustration
bot_token: "1234567890:AAHDcNdzR5fEnXgKoW9-xcEtAyKa9-KKFFk"

group_chat_id: "-896957154"

whisp_chat_id: "626778071"

# Fill with refresh seconds
refresh_seconds: 0.1

version: "v1.1.0-20230531"

timezone: "Asia/Taipei"

